FROM node:16-alpine
WORKDIR '/app'
COPY ./package.json ./
RUN npm config set unsafe-perm true
RUN npm install

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache
RUN chown -R node:node /app/node_modules

COPY . .
CMD ["npm", "run", "start"]
