name: Deploy multi
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t ${{ secrets.DOCKER_ID }}/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true ${{ secrets.DOCKER_ID }}/react-test npm test

      - run: docker build -t ${{ secrets.DOCKER_ID }}/multi-client ./client
      - run: docker build -t ${{ secrets.DOCKER_ID }}/multi-nginx ./nginx
      - run: docker build -t ${{ secrets.DOCKER_ID }}/multi-server ./server
      - run: docker build -t ${{ secrets.DOCKER_ID }}/multi-worker ./worker

      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_ID }} --password-stdin

      - run: docker push ${{ secrets.DOCKER_ID }}/multi-client
      - run: docker push ${{ secrets.DOCKER_ID }}/multi-nginx
      - run: docker push ${{ secrets.DOCKER_ID }}/multi-server
      - run: docker push ${{ secrets.DOCKER_ID }}/multi-worker

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-877202209361
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
